spring:
  application:
    name: Dockerized Steam Library Autoupdater
  lifecycle:
    timeout-per-shutdown-phase: 30s
  output:
    ansi:
      enabled: always
  cache:
    cache-names: steam-apps-data
    caffeine:
      spec: "maximumSize=500"
  config:
    import:
      - optional:env/application.properties

server:
  shutdown: graceful

app:
  http-client:
    steam:
      base-url: "https://store.steampowered.com"
      paths:
        app-details: "/api/appdetails"

steam:
  schedule: ${SCHEDULE:0 0 0-11 * * *}
  web-api-key: ${STEAM_WEB_API_KEY:}
  username: ${STEAM_USERNAME:anonymous}
  password: ${STEAM_PASSWORD:}
  root-path: ${STEAM_ROOT:/home/steam/Steam}
  cmd-root-path: ${STEAM_CMD_ROOT:/home/steam/steamcmd}
  cmd-filter-output: ${STEAM_CMD_FILTER_OUTPUT:true}
  cmd-validate-installed: ${STEAM_CMD_VALIDATE_INSTALLED:false}
  app-id-resolve-strategies: ${STEAM_APP_ID_RESOLVE_STRATEGY:MANUAL}
  manual-app-ids: ${STEAM_MANUAL_APP_IDS:740}
  ignore-app-ids: ${STEAM_IGNORE_APP_IDS:}
